const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94788185692"
const SESSION_ID = "PRABATH-MD~7Ac3VIQZ#pslGIGglMqrTKLPlk9_9MCszVbJUfT2EBeCdCMmVpzM"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
